import { User, Customer, Job, Notification } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'John Smith',
    role: 'admin',
    email: 'john@ furniflow.com',
    phone: '+1 234 567 8901',
    active: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-2',
    name: 'Sarah Johnson',
    role: 'sales',
    email: 'sarah@furniflow.com',
    phone: '+1 234 567 8902',
    active: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'user-3',
    name: 'Mike Wilson',
    role: 'service_head',
    email: 'mike@furniflow.com',
    phone: '+1 234 567 8903',
    active: true,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'user-4',
    name: 'Tom Davis',
    role: 'field_staff',
    email: 'tom@furniflow.com',
    phone: '+1 234 567 8904',
    active: true,
    createdAt: new Date('2024-02-15'),
  },
  {
    id: 'user-5',
    name: 'Emily Brown',
    role: 'field_staff',
    email: 'emily@furniflow.com',
    phone: '+1 234 567 8905',
    active: true,
    createdAt: new Date('2024-03-01'),
  },
  {
    id: 'user-6',
    name: 'Chris Lee',
    role: 'sales',
    email: 'chris@furniflow.com',
    phone: '+1 234 567 8906',
    active: true,
    createdAt: new Date('2024-03-15'),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Robert Anderson',
    phone: '+1 555 123 4567',
    address: '123 Oak Street, Springfield, IL 62701',
    product: 'Modern Sofa Set',
    inquiryDate: new Date('2024-03-10'),
    expectedClosingDate: new Date('2024-03-25'),
    notes: 'Interested in white leather options',
    status: 'lead',
    followUpDate: new Date('2024-03-20'),
    createdBy: 'user-2',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'cust-2',
    name: 'Jennifer Martinez',
    phone: '+1 555 234 5678',
    address: '456 Maple Ave, Chicago, IL 60601',
    product: 'Dining Table - 6 Seater',
    inquiryDate: new Date('2024-03-08'),
    expectedClosingDate: new Date('2024-03-22'),
    notes: 'Prefers oak wood finish',
    status: 'prospect',
    followUpDate: new Date('2024-03-19'),
    createdBy: 'user-2',
    createdAt: new Date('2024-03-08'),
    updatedAt: new Date('2024-03-12'),
  },
  {
    id: 'cust-3',
    name: 'David Thompson',
    phone: '+1 555 345 6789',
    address: '789 Pine Road, Naperville, IL 60540',
    product: 'Bedroom Furniture Set',
    inquiryDate: new Date('2024-03-05'),
    expectedClosingDate: new Date('2024-03-20'),
    notes: 'Executive style bedroom set requested',
    status: 'confirmed',
    followUpDate: null,
    createdBy: 'user-6',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'cust-4',
    name: 'Lisa Garcia',
    phone: '+1 555 456 7890',
    address: '321 Elm Street, Aurora, IL 60505',
    product: 'Office Desk & Chair',
    inquiryDate: new Date('2024-03-01'),
    expectedClosingDate: new Date('2024-03-18'),
    notes: 'Home office setup',
    status: 'confirmed',
    followUpDate: null,
    createdBy: 'user-2',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-14'),
  },
  {
    id: 'cust-5',
    name: 'Michael Chen',
    phone: '+1 555 567 8901',
    address: '654 Cedar Lane, Joliet, IL 60431',
    product: 'Kids Bedroom Set',
    inquiryDate: new Date('2024-02-28'),
    expectedClosingDate: null,
    notes: 'Looking for eco-friendly options',
    status: 'closed',
    followUpDate: null,
    createdBy: 'user-6',
    createdAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-03-10'),
  },
];

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    customerId: 'cust-3',
    customerName: 'David Thompson',
    customerPhone: '+1 555 345 6789',
    address: '789 Pine Road, Naperville, IL 60540',
    product: 'Bedroom Furniture Set',
    type: 'delivery',
    status: 'pending',
    source: 'dispatch',
    scheduledDate: new Date('2024-03-21'),
    assignedTo: null,
    rescheduleReason: null,
    images: [],
    remarks: '',
    completedAt: null,
    createdBy: 'user-6',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'job-2',
    customerId: 'cust-4',
    customerName: 'Lisa Garcia',
    customerPhone: '+1 555 456 7890',
    address: '321 Elm Street, Aurora, IL 60505',
    product: 'Office Desk & Chair',
    type: 'installation',
    status: 'accepted',
    source: 'dispatch',
    scheduledDate: new Date('2024-03-20'),
    assignedTo: 'user-4',
    rescheduleReason: null,
    images: [],
    remarks: '',
    completedAt: null,
    createdBy: 'user-2',
    createdAt: new Date('2024-03-14'),
    updatedAt: new Date('2024-03-16'),
  },
  {
    id: 'job-3',
    customerId: 'cust-1',
    customerName: 'Robert Anderson',
    customerPhone: '+1 555 123 4567',
    address: '123 Oak Street, Springfield, IL 62701',
    product: 'Modern Sofa Set',
    type: 'service',
    status: 'completed',
    source: 'manual',
    scheduledDate: new Date('2024-03-18'),
    assignedTo: 'user-5',
    rescheduleReason: null,
    images: ['site-image-1.jpg', 'site-image-2.jpg'],
    remarks: 'Full setup completed. Customer satisfied.',
    completedAt: new Date('2024-03-18T14:30:00'),
    createdBy: 'user-3',
    createdAt: new Date('2024-03-16'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: 'job-4',
    customerId: 'cust-2',
    customerName: 'Jennifer Martinez',
    customerPhone: '+1 555 234 5678',
    address: '456 Maple Ave, Chicago, IL 60601',
    product: 'Dining Table - 6 Seater',
    type: 'service',
    status: 'scheduled',
    source: 'manual',
    scheduledDate: new Date('2024-03-22'),
    assignedTo: 'user-4',
    rescheduleReason: null,
    images: [],
    remarks: '',
    completedAt: null,
    createdBy: 'user-3',
    createdAt: new Date('2024-03-17'),
    updatedAt: new Date('2024-03-17'),
  },
  {
    id: 'job-5',
    customerId: 'cust-5',
    customerName: 'Michael Chen',
    customerPhone: '+1 555 567 8901',
    address: '654 Cedar Lane, Joliet, IL 60431',
    product: 'Kids Bedroom Set',
    type: 'delivery',
    status: 'delivered',
    source: 'dispatch',
    scheduledDate: new Date('2024-03-15'),
    assignedTo: 'user-5',
    rescheduleReason: null,
    images: [],
    remarks: '',
    completedAt: null,
    createdBy: 'user-6',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-15'),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-2',
    type: 'success',
    title: 'Job Completed',
    message: 'Installation at Robert Anderson\'s place is complete',
    read: false,
    createdAt: new Date('2024-03-18T14:30:00'),
  },
  {
    id: 'notif-2',
    userId: 'user-2',
    type: 'info',
    title: 'Job Scheduled',
    message: 'Delivery for David Thompson scheduled for Mar 21',
    read: false,
    createdAt: new Date('2024-03-16T10:00:00'),
  },
  {
    id: 'notif-3',
    userId: 'user-3',
    type: 'alert',
    title: 'New Dispatch Request',
    message: 'New delivery request from Sales for David Thompson',
    read: true,
    createdAt: new Date('2024-03-15T09:00:00'),
  },
];
